apiVersion: v1
kind: Service
metadata:
  name: toapp-service
spec:
  selector:
    app: toapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toapp
spec:
  selector:
    matchLabels:
      app: toapp
  replicas: 3 
  template:
    metadata:
      labels:
        app: toapp
    spec:
      containers:
      - name: toapp
        image: movista/toapp:4.4.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
