apiVersion: v1
kind: Service
metadata:
  name: toapp-service
spec:
  selector:
    app: toapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toapp
spec:
  selector:
    matchLabels:
      app: toapp
  replicas:  
  template:
    metadata:
      labels:
        app: toapp
    spec:
      containers:
      - name: toapp
        #image: movista/toapp:6.6.6
        #image: movista/randaprd:10.30.23
        #image: movista/randaprd:11.20.23.vs
        #image: movista/randaprd:11.20.23.vs1
        #image: movista/randaprd:01.22.24.vs2
        image: movista/randaprd:04.24.24.S03
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
