apiVersion: v1
kind: Service
metadata:
  name: toapp-service
spec:
  selector:
    app: toapp
  ports:
  - protocol: "TCP"
    port: 8501
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toapp
spec:
  selector:
    matchLabels:
      app: toapp
  replicas: 4
  template:
    metadata:
      labels:
        app: toapp
    spec:
      containers:
      - name: toapp
        image: movista/topapp:1.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
