apiVersion: v1
kind: Service
metadata:
  name: toapp-service
spec:
  selector:
    app: toapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toapp
spec:
  selector:
    matchLabels:
      app: toapp
  replicas:  
  template:
    metadata:
      labels:
        app: toapp
    spec:
      containers:
      - name: toapp
        #image: movista/toapp:1.0.11
        #image: movista/signature:1.1.2
        #image: movista/randaprd #10.5.23
        image: movista/randaprd:04.24.24.S03
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
